/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function seqCreateSocket(ee: object, fd?: number | undefined | null): void
export function seqSetNapiBufSize(ee: object, size: number): void
export function seqGetNapiBufSize(ee: object): number
export function seqStartRecv(ee: object): void
export function seqAddress(ee: object): string
export function seqListen(ee: object, bindpath: string, backlog: number): void
export function seqConnect(ee: object, serverPath: string): void
export function seqWrite(ee: object, buf: Buffer, offset: number, length: number, cb?: (...args: any[]) => any | undefined | null): void
export function seqClose(ee: object): void
export function seqShutdownWhenFlushed(ee: object): void
export function dgramCreateSocket(ee: object): void
export function dgramStartRecv(ee: object): void
export function dgramClose(ee: object): void
export function dgramBind(ee: object, bindpath: string): void
export function dgramAddress(ee: object): string
export function dgramGetRecvBufferSize(ee: object): number
export function dgramSetRecvBufferSize(ee: object, size: number): void
export function dgramGetSendBufferSize(ee: object): number
export function dgramSetSendBufferSize(ee: object, size: number): void
export function dgramSendTo(ee: object, buf: Buffer, offset: number, length: number, path: string, cb?: (...args: any[]) => any | undefined | null): void
export function startRecv(ee: object): void
