/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class DgramSocketWrap {
  constructor(recvCb: (...args: any[]) => any)
  bind(bindpath: string): void
  /**
  * buf, offset, length, path
  */
  sendTo(buf: Buffer, offset: number, length: number, path: string, cb: (...args: any[]) => any): void
  close(): void
}
